AppBase/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500


from AppBase.views import HomeView, CreateClient, CreateEmpleado, ListClienteView, CreateContractView, CreateAccidentView, ListContractView,ContractDetailView, ContractDetailPdf, ListPagosView, ContratoClientView, PagosContractView,ContratoEmpleadoView, PagosDetailView, AsesoriaClienteView, AsesoriaEspecialClienteView, AsesoriaClienteView, AsesoriasEmpleadoView, CapacitacioesEmpleadoView, VisitasEmpleadoView, DetalleAsesoriaView, VisitasClienteView, DetalleVisitaView, DetalleAsesoriaClienteView, DetalleVisitaEmpleadoView, ChecklistView, ClientesEmpleadoView, ClienteDetalle, PerfilUsuario, DetalleChecklist, TasaAccidentabildiadView, InformeVisitaEmp, InformeVisitaCliente, DetallePlanMejora, DetalleCapacitacionEmp, CrearCapacitacion, CapacitacionesView, DetalleCapacitacionView, Error404View, Error500View, ReporteAccidentabilidad, InformesClienteView, AccidentesPdf, ReporteVisita, VisitaPDF, ReporteVisitasGenerales,VisitaGeneralPDF, ModificarFechaVisitaView, SolicitarCapacitacionView, CrearAsesoriaEmp

app_name = 'base'

urlpatterns = [
    path('', HomeView, name='home'),

    path('profesional/ingresar/', CreateEmpleado, name='create-emp'),
    path('profesional/contratos/', ContratoEmpleadoView, name='contract-emp'),
    path('profesional/clientes/', ClientesEmpleadoView, name='client-emp'),

    path('actividades/asesorias/', AsesoriasEmpleadoView, name='asesorias-emp'),
    path('actividades/asesorias/detalle/<pk>/', DetalleAsesoriaView, name='asesorias-detalle-emp'),
    path('actividades/asesorias/crear/', CrearAsesoriaEmp, name='asesorias-create'),

    path('actividades/capacitaciones/', CapacitacioesEmpleadoView, name='capacitacion-emp'),
    path('actividades/capacitaciones/<pk>/detalle/', DetalleCapacitacionEmp, name='capacitacion-emp-detalle'),
    path('actividades/capacitaciones/ingresar', CrearCapacitacion, name='capacitacion-crear'),

    path('actividades/visitas/', VisitasEmpleadoView, name='visitas-emp'),
    path('actividades/visitas/detalle/<pk>/',  DetalleVisitaEmpleadoView, name='visitas-detalle-emp'),

    path('actividades/visitas/<pk>/checklist/',  ChecklistView, name='visita-checklist'),
    path('actividades/visitas/<pk>/informe/',  InformeVisitaEmp, name='visita-informe'),

    path('clientes/ingresar/', CreateClient, name='create-client'),

    path('cuenta/perfil/<pk>', PerfilUsuario, name='user-profile'),
    
    path('clientes/', ListClienteView, name='list-client'),
    path('clientes/contratos/', ContratoClientView, name='contract'),
    path('clientes/detalle/<pk>/', ClienteDetalle, name='client-detalle'),

    path('clientes/asesorias/', AsesoriaClienteView, name='asesoria-client'),
    path('clientes/asesorias/detalle/<pk>/', DetalleAsesoriaClienteView, name='asesoria-detalle'),
    path('clientes/asesorias/solicitud/', AsesoriaEspecialClienteView, name='asesoria-especial'),

    path('clientes/visitas/', VisitasClienteView, name='visita-client'),
    path('clientes/visitas/detalle/<pk>/', DetalleVisitaView, name='visita-detalle'),
    path('clientes/visitas/detalle/<pk>/asignar/fecha-hora/', ModificarFechaVisitaView, name='visita-update'),
    path('clientes/visitas/detalle/<pk>/checklist/', DetalleChecklist, name='visitadetalle-checklist'),
    path('clientes/visitas/detalle/<pk>/informe/', InformeVisitaCliente, name='visita-informe-cliente'),
    path('clientes/visitas/detalle/<pk>/plandemejora/', DetallePlanMejora, name='visita-mejora'),

    path('clientes/capacitaciones/', CapacitacionesView, name='capacitacion-client'),
    path('clientes/capacitaciones/detalle/<pk>/', DetalleCapacitacionView, name='capacitacion-detalle'),
    # path('clientes/capacitaciones/solicitud/', SolicitarCapacitacionView, name='capacitacion-crear'),

    path('clientes/accidentes/ingresar/', CreateAccidentView, name='create-accident'),
    path('clientes/accidentes/tasa/<pk>', TasaAccidentabildiadView, name='tasa-accident'),

    path('contratos/', ListContractView, name='list-contract'),
    path('contratos/ingresar/', CreateContractView, name='create-contract'),
    path('contratos/detalle/<id>/', ContractDetailView, name='contract-detail'),
    path('contratos/detalle/pdf/<pk>/', ContractDetailPdf.as_view(), name='contract-pdf'),


    path('pagos/', ListPagosView, name='pagos'),
    path('pagos/contrato/<pk>/', PagosContractView, name='pago-contract'),
    path('pagos/detalle/<pk>/', PagosDetailView, name='pago-detail'),

    path('informes/', InformesClienteView, name='reportes'),
    
    path('informes/<pk>/accidentes', ReporteAccidentabilidad, name='reporte-tasa'),
    path('informes/<pk>/accidentes/pdf', AccidentesPdf.as_view(), name='tasa-pdf'),

    path('informes/visita/<pk>/', ReporteVisita, name='reporte-visita'),
    path('informes/visita/<pk>/pdf', VisitaPDF.as_view(), name='visita-pdf'),

    path('informes/<pk>/visitas/', ReporteVisitasGenerales, name='reporte-visita-general'),
    path('informes/<pk>/visitas/pdf', VisitaGeneralPDF.as_view(), name='visita-general-pdf'),
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_view()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppBase.urls', namespace='base')),
    path('', include('AppUser.urls', namespace='user')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/informes/accidentes.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Reporte Tasa Anual - ControlRisk</title>
{% endblock %}

{% block link %}
<script src="{% static 'lib/highcharts/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/series-label.js' %}"></script>
<script src="{% static 'lib/highcharts//modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/accessibility.js' %}"></script>
{% endblock %}

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 360px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }

    .parent {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        grid-template-rows: repeat(7, 1fr);
        grid-column-gap: 12px;
        grid-row-gap: 14px;
    }

    .div1 {
        grid-area: 1 / 1 / 2 / 2;
    }

    .div2 {
        grid-area: 1 / 2 / 2 / 4;
    }

    .div2 p {
        font-size: 2rem;
    }

    .div3 {
        grid-area: 2 / 1 / 4 / 4;
    }

    .reporte-content {
        font-size: 20px;
    }

    .div4 {
        grid-area: 4 / 1 / 7 / 3;
    }

    .div5 {
        grid-area: 7 / 1 / 8 / 4;
    }

    .div6 {
        grid-area: 4 / 3 / 7 / 4;
    }
</style>

{% block contenido %}
<div class="title">
    <i class="uil uil-file-check-alt"></i>
    <span class="text">Informe Accidentes, Contrato : {{ rut }}-{{ year }}-{{ id }}</span>
</div>

<div class="parent">
    <div class="div1"></div>
    <div class="div2" style="margin-bottom: 20px">
        <h3 style="font-size: 2rem; ">Reporte de Accidentes : {{ inicio }} - {{ final }}</h3>
    </div>
    <div class="div3" style="margin-bottom: 20px;">
        <div>
            <h3 style="font-size: 20px">Datos Reporte</h3>
            <div class="reporte-content">
                <br>
                <p style="font-size: 13px; padding: 10px;">
                    En el presente informe se da a conocer la cantidad de accidentes sufridos por la EMPRESA {{empresa|upper}} RUT {{formatRut}}, perteneciente al rubro {{rubro|upper}}, NRO CONTRATO {{rut}}-{{year}}-{{c}} correspondiente al periodo {{inicio}} - {{final}}.
                </p>
            </div>
        </div>
    </div>
    <div class="div4">
        {% if cantidadAccidentes > 0 %}
        <figure class="highcharts-figure">
            <div id="container"></div>
            {% if chart %}
            <img src="data:image/png;base64, {{ chart | safe }}" alt="" class="chart" style="width: 90%;">
            {% endif %}
        </figure>
        {% else %}
        <div class="alerta">
            <img src="{% static 'images/report.png' %}" alt="">
            <div>
                <p>No registras accidentes asociados a este contrato</p>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="div5"> </div>
    <div class="div6" style="margin-bottom: 20px;">
        <div>
            <div class="reporte-content">
                <br>
                <p style="font-size: 13px; padding: 10px;">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Laborum sapiente placeat beatae illo iusto
                        quidem nulla, facere labore eveniet necessitatibus quam, debitis perferendis ad nostrum
                        veritatis
                        aspernatur delectus. Tempore, quos! Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Veniam
                        fugit cumque nobis tempora ipsam omnis libero, incidunt vitae nam sed molestias, unde dolore
                        recusandae doloremque, modi sit vero obcaecati? A.
                        <br> <br>
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. A nihil ad repellendus exercitationem
                        laudantium praesentium quod beatae, mollitia, eum fugit veritatis repudiandae omnis eos iusto
                        quo deleniti ex maxime nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis
                        et hic qui nostrum adipisci! Qui vel quibusdam provident eligendi aspernatur, accusamus
                        recusandae similique facere doloribus eos, cumque architecto, molestiae dolor! Lorem ipsum dolor
                        sit amet consectetur, adipisicing elit. Distinctio earum recusandae veritatis, quas ipsa
                        dolores, delectus ut quasi magnam sequi rem! Repellendus, consequuntur quis. Quisquam doloremque
                        vitae nostrum placeat et?
                </p>
            </div>
        </div>
    </div>
    <div class="boton">
        {% if cantidadAccidentes > 0 %}
        <div class="button-c pdf">
            <a class="btn" href="{% url 'base:tasa-pdf' id  %}" target="_blank">Generar pdf de informe</a>
        </div>
        {% else %}
        <div class="button-c pdf">
            <p class="btn">No es posible generar pdf</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/informes/informe_visita.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Informe Visita - ControlRisk</title>
{% endblock %}

{% block link %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
{% endblock %}

{% block contenido %}
<div class="title">
    <i class="uil uil-file-check-alt"></i>
    <span class="text">Informe, Visita : {{ id }}</span>
</div>

<div class="container">
    <form action="#" method="POST" id="form-asesoria">
        {% csrf_token %}
        <div class="form first">
            <div class="details personal">
                <div class="fields">
                    {% for i in visita %}
                    <div class="input-field direc" id="input-field-fecha">
                        <label>Empresa</label>
                        <input type="text" disabled value="{{ i.0 }}" name="empresa">
                    </div>
                    <div class="input-field" id="input-field-fecha">
                        <label>Fecha Visita</label>
                        <input type="text" value="{{ i.2 }}" disabled name="fecha">
                    </div>
                    <div class="input-field repre" id="input-field-fecha">
                        <label>Rut Empresa</label>

                        <input type="text" disabled value="{{ i.1 }}" name="rut">
                    </div>
                    <div class="input-field direc" id="input-field-fecha">
                        <label>Situación de la Empresa a la que se le realizó la visita</label>

                        <textarea name="situacion" id="" cols="100" rows="50" required></textarea>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="details ID">
                <button class="nextBtn" type="submit" id="btn" name="btninforme">
                    <span class="btnText">Guardar</span>
                    <i class="uil uil-navigator"></i>
                </button>
                <button type="button" class="nextBtn" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    AGREGAR PLAN DE MEJORA
                </button>
            </div>
        </div>
    </form>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Ingresar Plan de Mejora</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="#" method="POST" id="form-asesoria">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="message-text" class="col-form-label fs-4">Plan Mejora :</label>
                            <textarea class="form-control fs-4" id="message-text" rows="15" required name="mejora"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary fs-4 p-3 m-3" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary fs-4 p-3 m-3" name="btnmejora">Guardar Plan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% if messages %}
    {% for m in messages %}
    {% if m.tags == 'success' %}
    <script>
        Swal.fire({
            'tittle': 'Exito',
            'icon': 'success',
            'text': '{{ m }}',
            'confirmButtonColor': '#ff131d',
            'confirmButtonText': 'Aceptar',
        })
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% if messages %}
    {% for m in messages %}
    {% if m.tags == 'error' %}
    <script>
        Swal.fire({
            'tittle': 'Exito',
            'icon': 'error',
            'text': '{{ m }}',
            'confirmButtonColor': '#ff131d',
            'confirmButtonText': 'Aceptar',
        })
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/informes/informes.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Informes - ControlRisk</title>
{% endblock %}

{% block contenido %}
<div class="title">
    <i class="uil uil-invoice"></i>
    <span class="text">Informes</span>
</div>

<div class="dash-content">
    {% if c > 0 %}
    <h2>Contrato Activo</h2>
    {% for c in entity %}
    <div class="acordion-pagos">
        <div style="margin-top: 20px">
            <details close>
                <summary>
                    <p><i class="uil uil-document-layout-left"></i> Informes Asociados al Contrato
                        {{c.20}}-{{c.19}}-{{c.0}}</p>
                </summary>
                <div>
                    <details class="secundary">
                        <summary>
                            <a href='{% url "base:reporte-tasa" c.0 %}'>
                                <i class="uil uil-accessible-icon-alt"></i> Informe de Accidentes
                            </a>
                        </summary>
                    </details>
                    <details class="secundary">
                        <summary>
                            <a href='{% url "base:reporte-visita-general" c.0 %}'>
                                <i class="uil uil-check-circle"></i> Informe General de Visitas
                            </a>
                        </summary>
                    </details>
                    <details close>
                        <summary class="secundary">
                            <p><i class="uil uil-check-circle"></i> Informe de Visitas</p>
                        </summary>
                        <div class="visit">
                            {% for i in visitas %}
                            <a href="{% url 'base:reporte-visita' i.0 %}"><i class="uil uil-car"></i> Visita - Fecha :
                                {{i.1}}</a><br>
                            {% endfor %}
                        </div>
                    </details>
                </div>
            </details>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="alerta">
        <img src="{% static 'images/pay.png' %}" alt="">
        <p>Tus informes aparecerán aquí</p>
    </div>
    {% endif %}

    {% if contratos %}
    <h2>Contrato Inactivos</h2>
    {% for c in contratos %}
    <div class="acordion-pagos">
        <div style="margin-top: 20px">
            <details close>
                <summary>
                    <p><i class="uil uil-document-layout-left"></i> Informes Asociados al Contrato
                        {{c.20}}-{{c.19}}-{{c.0}}</p>
                </summary>
                <div>
                    <details class="secundary">
                        <summary>
                            <a href='{% url "base:reporte-tasa" c.0 %}'>
                                <i class="uil uil-accessible-icon-alt"></i> Informe de Accidentes
                            </a>
                        </summary>
                    </details>
                    <details class="secundary">
                        <summary>
                            <a href='{% url "base:reporte-visita-general" c.0 %}'>
                                <i class="uil uil-check-circle"></i> Informe General de Visitas
                            </a>
                        </summary>
                    </details>
                    <details close>
                        <summary class="secundary">
                            <p><i class="uil uil-check-circle"></i> Informe de Visitas</p>
                        </summary>
                        <div class="visit">
                            {% for i in visitas %}
                            <a href="{% url 'base:reporte-visita' i.0 %}"><i class="uil uil-car"></i> Visita - Fecha :
                                {{i.1}}</a><br>
                            {% endfor %}
                        </div>
                    </details>
                </div>
            </details>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
</div>
{% endblock %}

templates/informes/visitas_generales.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Reporte de Visita General- ControlRisk</title>
{% endblock %}

{% block link %}
<script src="{% static 'lib/highcharts/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/series-label.js' %}"></script>
<script src="{% static 'lib/highcharts//modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/accessibility.js' %}"></script>
{% endblock %}

<style>
    .highcharts-figure,
    .highcharts-data-table table {
        min-width: 360px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #ebebeb;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td,
    .highcharts-data-table th,
    .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr,
    .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }

    .parent {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        grid-template-rows: repeat(7, 1fr);
        grid-column-gap: 12px;
        grid-row-gap: 14px;
    }

    .div1 {
        grid-area: 1 / 1 / 2 / 2;
    }

    .div2 {
        grid-area: 1 / 2 / 2 / 4;
    }

    .div2 p {
        font-size: 2rem;
    }

    .div3 {
        grid-area: 2 / 1 / 4 / 4;
    }

    .reporte-content {
        font-size: 20px;
    }

    .div4 {
        width: 100%;
        grid-area: 4 / 1 / 7 / 3;
    }

    .div5 {
        grid-area: 7 / 1 / 8 / 4;
    }

    .div6 {
        grid-area: 4 / 3 / 7 / 4;
    }

    #container {
        width: 100%;
        display: flex;
        justify-content: center;
    }

    .check {
        display: flex;
        justify-content: centers;
    }
</style>

{% block contenido %}
<div class="title">
    <i class="uil uil-file-check-alt"></i>
    <span class="text">Informe General de Visitas Periodo : {{ inicio }} - {{ final }}</span>
</div>

<div class="parent">
    <div class="div1">
        
    <br>
    <div class="div2" style="margin-bottom: 20px">
        <h3 style="font-size: 2rem; ">Reporte General de Visitas Realizadas en el Periodo del Contrato</h3>
    </div>
    <div class="div3" style="margin-bottom: 20px;">
        <div>
            <h3 style="font-size: 20px">Información General de la Visita</h3>
            <div class="reporte-content">
                <br>
                <p style="font-size: 13px; padding: 10px;">
                    En el presente informe se da a conocer el resultados de las LISTAS DE CHEQUEO de todas las visitas
                    de la EMPRESA {{empresa|upper}} RUT {{formatRut}} CONTRATO {{rut}}-{{annio}}-{{cid}} realizadas
                    entre {{inicio}} - {{final}}.
                </p>
            </div>
        </div>
    </div>
    {% if total > 0 %}
    <div class="div4">
        <figure class="highcharts-figure">
            <div id="container" style="margin-top: 40px">
                {% if chart %}
                <img src="data:image/png;base64, {{ chart | safe }}" alt="" class="chart">
                {% endif %}
            </div>
        </figure>
        <br>
        <br>
        <br>
        <figure class="highcharts-figure-pie">
            <div id="container-pie">
            </div>
        </figure>
        <br>
        <br>
        <br>
        <div>
            <h3 style="font-size: 20px">Información Obtenida de las Graficas</h3>
            <div class="reporte-content">
                <p style="font-size: 13px; padding: 10px;">
                    De acuerdo a las graficas visualziadas anteriormente, se observa que la empresa {{ empresa | upper}}
                    rut {{formatRut}} de un total de {{total}} ITEMS (Contanto todos los items de cada visita
                    realizada), obtuvo {{ap}} ITEMS APROBADOS (Que corresponde a un {{ porc_aprobado}}%), {{sa}} ITEMS
                    SEMI APROBADOS (Que corresponde a un {{ porc_semi}}%) y {{re}} ITEMS REPROBADOS (Que corresponde a
                    un {{ porc_reprobado}}%).
                </p>
            </div>
        </div>
    </div>
    {% else %}
    <div class="alerta">
        <img src="{% static 'images/report.png' %}" alt="">
        <div>
            <p>La visita aún no se ha realizado</p>
        </div>
    </div>
    {% endif %}
    
    {% if total > 0 %}
    <div class="boton" style="display:flex; justify-content: space-around;">
        <div class="button-c pdf">
            <a class="btn" href="{% url 'base:visita-general-pdf' cid %}" target="_blank">Generar pdf de informe</a>
        </div>
        <!-- <div class="button-c pdf">
            <form action="" method="post">
                {% csrf_token %}
                <button class="btn" name="email" href="{% url 'base:visita-pdf' id %}" target="_blank">Enviar informe
                    via email</button>
            </form>
        </div> -->
    </div>
    {% else %}
    <div class="boton" style="display:flex; justify-content: space-around;">
        <div class="button-c pdf">
            <p class="btn">No se puede generar pdf</p>
        </div>
        <!-- <div class="button-c pdf">
            <form action="" method="post">
                {% csrf_token %}
                <button class="btn" name="email" href="{% url 'base:visita-pdf' id %}" target="_blank">Enviar informe
                    via email</button>
            </form>
        </div> -->
    </div>
    {% endif %}

    <script type=text/javascript>
        Highcharts.chart('container-pie', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Porcentaje resultado de Lista de Cheoqueo {{ empresa | upper }}'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                name: 'Porcentaje',
                colorByPoint: true,
                data: [{
                    name: 'Reprobado',
                    y: {{ porc_reprobado }},
                sliced: true,
                selected: true
                }, {
            name: 'Semi Aprobado',
            y: {{ porc_semi }}
                }, {
                name: 'Aprobado',
                y: {{ porc_aprobado }},
                }]
            }]
        });


    </script>
</div>
{% endblock %}