AppBase/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500


from AppBase.views import HomeView, CreateClient, CreateEmpleado, ListClienteView, CreateContractView, CreateAccidentView, ListContractView,ContractDetailView, ContractDetailPdf, ListPagosView, ContratoClientView, PagosContractView,ContratoEmpleadoView, PagosDetailView, AsesoriaClienteView, AsesoriaEspecialClienteView, AsesoriaClienteView, AsesoriasEmpleadoView, CapacitacioesEmpleadoView, VisitasEmpleadoView, DetalleAsesoriaView, VisitasClienteView, DetalleVisitaView, DetalleAsesoriaClienteView, DetalleVisitaEmpleadoView, ChecklistView, ClientesEmpleadoView, ClienteDetalle, PerfilUsuario, DetalleChecklist, TasaAccidentabildiadView, InformeVisitaEmp, InformeVisitaCliente, DetallePlanMejora, DetalleCapacitacionEmp, CrearCapacitacion, CapacitacionesView, DetalleCapacitacionView, Error404View, Error500View, ReporteAccidentabilidad, InformesClienteView, AccidentesPdf, ReporteVisita, VisitaPDF, ReporteVisitasGenerales,VisitaGeneralPDF, ModificarFechaVisitaView, SolicitarCapacitacionView, CrearAsesoriaEmp

app_name = 'base'

urlpatterns = [
    path('', HomeView, name='home'),

    path('profesional/ingresar/', CreateEmpleado, name='create-emp'),
    path('profesional/contratos/', ContratoEmpleadoView, name='contract-emp'),
    path('profesional/clientes/', ClientesEmpleadoView, name='client-emp'),

    path('actividades/asesorias/', AsesoriasEmpleadoView, name='asesorias-emp'),
    path('actividades/asesorias/detalle/<pk>/', DetalleAsesoriaView, name='asesorias-detalle-emp'),
    path('actividades/asesorias/crear/', CrearAsesoriaEmp, name='asesorias-create'),

    path('actividades/capacitaciones/', CapacitacioesEmpleadoView, name='capacitacion-emp'),
    path('actividades/capacitaciones/<pk>/detalle/', DetalleCapacitacionEmp, name='capacitacion-emp-detalle'),
    path('actividades/capacitaciones/ingresar', CrearCapacitacion, name='capacitacion-crear'),

    path('actividades/visitas/', VisitasEmpleadoView, name='visitas-emp'),
    path('actividades/visitas/detalle/<pk>/',  DetalleVisitaEmpleadoView, name='visitas-detalle-emp'),

    path('actividades/visitas/<pk>/checklist/',  ChecklistView, name='visita-checklist'),
    path('actividades/visitas/<pk>/informe/',  InformeVisitaEmp, name='visita-informe'),

    path('clientes/ingresar/', CreateClient, name='create-client'),

    path('cuenta/perfil/<pk>', PerfilUsuario, name='user-profile'),
    
    path('clientes/', ListClienteView, name='list-client'),
    path('clientes/contratos/', ContratoClientView, name='contract'),
    path('clientes/detalle/<pk>/', ClienteDetalle, name='client-detalle'),

    path('clientes/asesorias/', AsesoriaClienteView, name='asesoria-client'),
    path('clientes/asesorias/detalle/<pk>/', DetalleAsesoriaClienteView, name='asesoria-detalle'),
    path('clientes/asesorias/solicitud/', AsesoriaEspecialClienteView, name='asesoria-especial'),

    path('clientes/visitas/', VisitasClienteView, name='visita-client'),
    path('clientes/visitas/detalle/<pk>/', DetalleVisitaView, name='visita-detalle'),
    path('clientes/visitas/detalle/<pk>/asignar/fecha-hora/', ModificarFechaVisitaView, name='visita-update'),
    path('clientes/visitas/detalle/<pk>/checklist/', DetalleChecklist, name='visitadetalle-checklist'),
    path('clientes/visitas/detalle/<pk>/informe/', InformeVisitaCliente, name='visita-informe-cliente'),
    path('clientes/visitas/detalle/<pk>/plandemejora/', DetallePlanMejora, name='visita-mejora'),

    path('clientes/capacitaciones/', CapacitacionesView, name='capacitacion-client'),
    path('clientes/capacitaciones/detalle/<pk>/', DetalleCapacitacionView, name='capacitacion-detalle'),
    # path('clientes/capacitaciones/solicitud/', SolicitarCapacitacionView, name='capacitacion-crear'),

    path('clientes/accidentes/ingresar/', CreateAccidentView, name='create-accident'),
    path('clientes/accidentes/tasa/<pk>', TasaAccidentabildiadView, name='tasa-accident'),

    path('contratos/', ListContractView, name='list-contract'),
    path('contratos/ingresar/', CreateContractView, name='create-contract'),
    path('contratos/detalle/<id>/', ContractDetailView, name='contract-detail'),
    path('contratos/detalle/pdf/<pk>/', ContractDetailPdf.as_view(), name='contract-pdf'),


    path('pagos/', ListPagosView, name='pagos'),
    path('pagos/contrato/<pk>/', PagosContractView, name='pago-contract'),
    path('pagos/detalle/<pk>/', PagosDetailView, name='pago-detail'),

    path('informes/', InformesClienteView, name='reportes'),
    
    path('informes/<pk>/accidentes', ReporteAccidentabilidad, name='reporte-tasa'),
    path('informes/<pk>/accidentes/pdf', AccidentesPdf.as_view(), name='tasa-pdf'),

    path('informes/visita/<pk>/', ReporteVisita, name='reporte-visita'),
    path('informes/visita/<pk>/pdf', VisitaPDF.as_view(), name='visita-pdf'),

    path('informes/<pk>/visitas/', ReporteVisitasGenerales, name='reporte-visita-general'),
    path('informes/<pk>/visitas/pdf', VisitaGeneralPDF.as_view(), name='visita-general-pdf'),
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_view()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppBase.urls', namespace='base')),
    path('', include('AppUser.urls', namespace='user')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/asesorias/asesoria_especial.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Clientes - ControlRisk</title>
{% endblock %}

{% block contenido %}
<div class="title">
    <i class="uil uil-thumbs-up"></i>
    <span class="text">Solicitud de Asesorias Especial</span>
</div>

<div class="container">
    <form action="#" method="POST" id="form-asesoria">
        {% csrf_token %}
        <div class="form first">
            <div class="details personal">
                <div class="fields">
                    <div class="input-field repre" id="input-field-fecha">
                        <label>Fecha para Asesoria</label>
                        {{ especialForm.fecha }}
                        <p class="alert-input" id="alert-input">
                            <i class="uil uil-exclamation-circle"></i> 
                            La fecha ingresada no puede ser inferior a 
                        </p>
                    </div>
                    <div class="input-field" id="input-field-hora">
                        <label>Hora para Asesoria </label>
                        {{ especialForm.hora }}
                        <p class="alert-input" id="alert-input">
                            <i class="uil uil-exclamation-circle"></i> 
                            La hora ingresada debe ser entre las 10:00 am y las 16:00 pm
                        </p>
                    </div>
                </div>
            </div>

            <div class="details ID">
                <div class="fields">

                    <div class="input-field direc" id="input-field-repre">
                        <label>Descripcions o motivo de solicitud</label>
                        {{ especialForm.descripcion }}
                        <p class="alert-input" id="alert-input">
                            <i class="uil uil-exclamation-circle"></i> 
                            Ingrese nombres validos (Pedro Juan Perez Perez)
                        </p>
                    </div>
                </div>

                <button class="nextBtn" type="submit" id="btn">
                    <span class="btnText">Guardar</span>
                    <i class="uil uil-navigator"></i>
                </button>
            </div> 
        </div>
    </form>

    {% if messages %}
        {% for m in messages %}
                {% if m.tags  == 'success' %}
                <script>
                    Swal.fire({
                        'tittle': 'Exito',
                        'icon': 'success',
                        'text': '{{ m }}',
                        'confirmButtonColor': '#ff131d',
                        'confirmButtonText': 'Aceptar',
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if messages %}
        {% for m in messages %}
            {% if m.tags  == 'error' %}
                <script>
                    Swal.fire({
                        'tittle': 'Exito',
                        'icon': 'error',
                        'text': '{{ m }}',
                        'confirmButtonColor': '#ff131d',
                        'confirmButtonText': 'Aceptar',
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

{% block javascript %}
<script src='{% static "js/validate-asesoria.js" %}'></script>
{% endblock %}

templates/asesorias/asesorias_cliente.html
{% extends 'base.html' %} {% load static %} {% block name %}
<title>Asesorias - ControlRisk</title>
{% endblock %} {% block contenido %}
<div class="title">
    <i class="uil uil-thumbs-up"></i>
    <span class="text">Asesorias, Cliente : {{ rut }}</span>
</div>

{% if activo == 1 %}
<div class="especial">
    <a href="{% url 'base:asesoria-especial' %}">Solicitar asesoria especial <i class="uil uil-arrow-right"></i></a>
</div>

<div class="dash-content" class="table-container">
    <h2 style="text-align: center" class="act">ESTAS SON TUS ASESORIAS DEL MES</h2>
    {% if c > 0 %}
    <table class="table-rwd">
        <thead>
            <tr>
                <th style="text-transform: uppercase">Asesoria ID</th>
                <th style="text-transform: uppercase">Fecha Asesoria</th>
                <th style="text-transform: uppercase">Estado</th>
                <th style="text-transform: uppercase">Hora</th>
                <th style="text-transform: uppercase">Extra</th>
                <th style="text-transform: uppercase">Rut Empleado</th>
                <th style="text-transform: uppercase">Nombre Empleado</th>
                <th style="text-transform: uppercase">Detalle</th>
            </tr>
        </thead>
        <tbody>
            {% for item in mesuales %}
            <tr>
                <td data-titulo="Asesoria ID">{{ item.0 }}</td>
                <td data-titulo="Fecha Asesoria">
                    <div id="fechasesoria">{{ item.1 }}</div>
                </td>
                <td data-titulo="Estado">{{ item.3 }}</td>
                <td data-titulo="Hora">{{ item.2 }}</td>
                {% if item.4 == True %}
                <td class="container-status" data-titulo="Extra">
                    <div class="centrar">
                        <p>SI</p>
                    </div>
                </td>
                {% else %}
                <td class="container-status" data-titulo="Extra">
                    <div class="centrar">
                        <p>NO</p>
                    </div>
                </td>
                {% endif %}
                <td data-titulo="Rut Empleado">
                    <div id="rutempleado">{{ item.5 }}</div>
                </td>
                <td data-titulo="Nombre Empleado">{{ item.6 | upper }}</td>
                <td>
                    <a href="{% url 'base:asesoria-detalle' item.0 %}" class="detail">
                        <i class="uil uil-external-link-alt"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alerta">
        <p>NO PRESENTAS ASESORIAS PARA EL MES ACTUAL</p>
    </div>
    {% endif %}
    <br> <br><br>
    <h2 style="text-align: center" class="act">ESTAS SON TUS ASESORIAS</h2>
    <table class="table-rwd">
        <thead>
            <tr>
                <th style="text-transform: uppercase">Asesoria ID</th>
                <th style="text-transform: uppercase">Fecha Asesoria</th>
                <th style="text-transform: uppercase">Estado</th>
                <th style="text-transform: uppercase">Hora</th>
                <th style="text-transform: uppercase">Extra</th>
                <th style="text-transform: uppercase">Rut Empleado</th>
                <th style="text-transform: uppercase">Nombre Empleado</th>
                <th style="text-transform: uppercase">Detalle</th>
            </tr>
        </thead>
        <tbody>
            {% for item in entity %}
            <tr>
                <td data-titulo="Asesoria ID">{{ item.0 }}</td>
                <td data-titulo="Fecha Asesoria">
                    <div id="fechasesoria">{{ item.1 }}</div>
                </td>
                <td data-titulo="Estado">{{ item.3 }}</td>
                <td data-titulo="Hora">{{ item.2 }}</td>
                {% if item.4 == True %}
                <td class="container-status" data-titulo="Extra">
                    <div class="centrar">
                        <p>SI</p>
                    </div>
                </td>
                {% else %}
                <td class="container-status" data-titulo="Extra">
                    <div class="centrar">
                        <p>NO</p>
                    </div>
                </td>
                {% endif %}
                <td data-titulo="Rut Empleado">
                    <div id="rutempleado">{{ item.5 }}</div>
                </td>
                <td data-titulo="Nombre Empleado">{{ item.6 | upper }}</td>
                <td>
                    <a href="{% url 'base:asesoria-detalle' item.0 %}" class="detail">
                        <i class="uil uil-external-link-alt"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="dash-content" class="table-container">
    <div class="alerta">
        <img src="{% static 'images/contract.svg' %}" alt="" style="max-width: 250px">
        <p>No presentas un contrato activo</p>
    </div>
</div>
{% endif %}
{% endblock %}

templates/asesorias/detalle_asesoria_cliente.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Visitas - ControlRisk</title>
{% endblock %}

{% block contenido %}
<div class="title">
    <i class="uil uil-thumbs-up"></i>
    <span class="text">Detalle de Asesoria</span>
</div>

<div class="dash-content">
    <div class="container-card">
        <div class="card">
            {% for item in entity %}
            <div class="card-detail">
                <h3>NRO. Asesoria : </h3>
                <p>{{ item.0 }}</p>
            </div>
            <div class="card-detail">
                <h3>Rut Empleado Encargado : </h3>
                <p>{{ item.12 }}</p>
            </div>
            <div class="card-detail">
                <h3>Nombre Empleado Encargado : </h3>
                <p>{{ item.11 }}</p>
            </div>
            <div class="card-detail">
                <h3>Estado Asesoria : </h3>
                <p>{{ item.4 }}</p>
            </div>
            <div class="card-detail">
                <h3>Fecha Asesoria : </h3>
                <p>{{ item.1 }}</p>
            </div>
            <div class="card-detail">
                <h3>Hora Asesoria : </h3>
                <p>{{ item.2 }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}