AppBase/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500


from AppBase.views import HomeView, CreateClient, CreateEmpleado, ListClienteView, CreateContractView, CreateAccidentView, ListContractView,ContractDetailView, ContractDetailPdf, ListPagosView, ContratoClientView, PagosContractView,ContratoEmpleadoView, PagosDetailView, AsesoriaClienteView, AsesoriaEspecialClienteView, AsesoriaClienteView, AsesoriasEmpleadoView, CapacitacioesEmpleadoView, VisitasEmpleadoView, DetalleAsesoriaView, VisitasClienteView, DetalleVisitaView, DetalleAsesoriaClienteView, DetalleVisitaEmpleadoView, ChecklistView, ClientesEmpleadoView, ClienteDetalle, PerfilUsuario, DetalleChecklist, TasaAccidentabildiadView, InformeVisitaEmp, InformeVisitaCliente, DetallePlanMejora, DetalleCapacitacionEmp, CrearCapacitacion, CapacitacionesView, DetalleCapacitacionView, Error404View, Error500View, ReporteAccidentabilidad, InformesClienteView, AccidentesPdf, ReporteVisita, VisitaPDF, ReporteVisitasGenerales,VisitaGeneralPDF, ModificarFechaVisitaView, SolicitarCapacitacionView, CrearAsesoriaEmp

app_name = 'base'

urlpatterns = [
    path('', HomeView, name='home'),

    path('profesional/ingresar/', CreateEmpleado, name='create-emp'),
    path('profesional/contratos/', ContratoEmpleadoView, name='contract-emp'),
    path('profesional/clientes/', ClientesEmpleadoView, name='client-emp'),

    path('actividades/asesorias/', AsesoriasEmpleadoView, name='asesorias-emp'),
    path('actividades/asesorias/detalle/<pk>/', DetalleAsesoriaView, name='asesorias-detalle-emp'),
    path('actividades/asesorias/crear/', CrearAsesoriaEmp, name='asesorias-create'),

    path('actividades/capacitaciones/', CapacitacioesEmpleadoView, name='capacitacion-emp'),
    path('actividades/capacitaciones/<pk>/detalle/', DetalleCapacitacionEmp, name='capacitacion-emp-detalle'),
    path('actividades/capacitaciones/ingresar', CrearCapacitacion, name='capacitacion-crear'),

    path('actividades/visitas/', VisitasEmpleadoView, name='visitas-emp'),
    path('actividades/visitas/detalle/<pk>/',  DetalleVisitaEmpleadoView, name='visitas-detalle-emp'),

    path('actividades/visitas/<pk>/checklist/',  ChecklistView, name='visita-checklist'),
    path('actividades/visitas/<pk>/informe/',  InformeVisitaEmp, name='visita-informe'),

    path('clientes/ingresar/', CreateClient, name='create-client'),

    path('cuenta/perfil/<pk>', PerfilUsuario, name='user-profile'),
    
    path('clientes/', ListClienteView, name='list-client'),
    path('clientes/contratos/', ContratoClientView, name='contract'),
    path('clientes/detalle/<pk>/', ClienteDetalle, name='client-detalle'),

    path('clientes/asesorias/', AsesoriaClienteView, name='asesoria-client'),
    path('clientes/asesorias/detalle/<pk>/', DetalleAsesoriaClienteView, name='asesoria-detalle'),
    path('clientes/asesorias/solicitud/', AsesoriaEspecialClienteView, name='asesoria-especial'),

    path('clientes/visitas/', VisitasClienteView, name='visita-client'),
    path('clientes/visitas/detalle/<pk>/', DetalleVisitaView, name='visita-detalle'),
    path('clientes/visitas/detalle/<pk>/asignar/fecha-hora/', ModificarFechaVisitaView, name='visita-update'),
    path('clientes/visitas/detalle/<pk>/checklist/', DetalleChecklist, name='visitadetalle-checklist'),
    path('clientes/visitas/detalle/<pk>/informe/', InformeVisitaCliente, name='visita-informe-cliente'),
    path('clientes/visitas/detalle/<pk>/plandemejora/', DetallePlanMejora, name='visita-mejora'),

    path('clientes/capacitaciones/', CapacitacionesView, name='capacitacion-client'),
    path('clientes/capacitaciones/detalle/<pk>/', DetalleCapacitacionView, name='capacitacion-detalle'),
    # path('clientes/capacitaciones/solicitud/', SolicitarCapacitacionView, name='capacitacion-crear'),

    path('clientes/accidentes/ingresar/', CreateAccidentView, name='create-accident'),
    path('clientes/accidentes/tasa/<pk>', TasaAccidentabildiadView, name='tasa-accident'),

    path('contratos/', ListContractView, name='list-contract'),
    path('contratos/ingresar/', CreateContractView, name='create-contract'),
    path('contratos/detalle/<id>/', ContractDetailView, name='contract-detail'),
    path('contratos/detalle/pdf/<pk>/', ContractDetailPdf.as_view(), name='contract-pdf'),


    path('pagos/', ListPagosView, name='pagos'),
    path('pagos/contrato/<pk>/', PagosContractView, name='pago-contract'),
    path('pagos/detalle/<pk>/', PagosDetailView, name='pago-detail'),

    path('informes/', InformesClienteView, name='reportes'),
    
    path('informes/<pk>/accidentes', ReporteAccidentabilidad, name='reporte-tasa'),
    path('informes/<pk>/accidentes/pdf', AccidentesPdf.as_view(), name='tasa-pdf'),

    path('informes/visita/<pk>/', ReporteVisita, name='reporte-visita'),
    path('informes/visita/<pk>/pdf', VisitaPDF.as_view(), name='visita-pdf'),

    path('informes/<pk>/visitas/', ReporteVisitasGenerales, name='reporte-visita-general'),
    path('informes/<pk>/visitas/pdf', VisitaGeneralPDF.as_view(), name='visita-general-pdf'),
]

handler404 = Error404View.as_view()
handler500 = Error500View.as_view()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppBase.urls', namespace='base')),
    path('', include('AppUser.urls', namespace='user')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block name %}
    <title></title>
    {% endblock %}
    <link rel="stylesheet" href='{% static "css/styles.css" %}' />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="icon" href="{% static 'images/prevencion.png'%}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block link %}

    {% endblock %}
    {% block styles %}
    
    {% endblock %}
</head>

<body>
    <nav>
        <div class="logo-name">
            <div class="logo-image">
                <img src='{% static "images/prevencion.png" %}' alt="">
            </div>

            <span class="logo_name">ControlRisk</span>
        </div>

        <div class="menu-items">
            <ul class="nav-links">
                <li><a href='{% url "base:home" %}'>
                        <i class="uil uil-estate"></i>
                        <span class="link-name">Inicio</span>
                    </a></li>
                {% if user.is_staff == 1 %}
                {% if user.is_profesional == 0 %}
                <li><a href='{% url "base:list-client" %}'>
                        <i class="uil uil-hard-hat"></i>
                        <span class="link-name">Clientes</span>
                    </a></li>
                <li><a href='{% url "base:create-emp" %}'>
                        <i class="uil uil-users-alt"></i>
                        <span class="link-name">Empleados</span>
                    </a></li>
                <li><a href='{% url "base:list-contract" %}'>
                        <i class="uil uil-file-contract-dollar"></i>
                        <span class="link-name">Contratos</span>
                    </a></li>
                {% endif %}
                {% endif %}

                {% if user.is_staff == 0 %}
                {% if user.is_profesional == 1 %}
                <li><a href='{% url "base:client-emp" %}'>
                        <i class="uil uil-hard-hat"></i>
                        <span class="link-name">Clientes</span>
                    </a></li>
                <li><a href='{% url "base:contract-emp" %}'>
                        <i class="uil uil-file-contract-dollar"></i>
                        <span class="link-name">Contratos</span>
                    </a></li>
                <li><a href="{% url 'base:capacitacion-emp' %}">
                        <i class="uil uil-podium"></i>
                        <span class="link-name">Capacitaciones</span>
                    </a></li>
                <li><a href="{% url 'base:visitas-emp' %}">
                        <i class="uil uil-car-sideview"></i>
                        <span class="link-name">Visitas</span>
                    </a></li>
                <li><a href="{% url 'base:asesorias-emp' %}">
                        <i class="uil uil-thumbs-up"></i>
                        <span class="link-name">Asesorias</span>
                        {% endif %}
                        {% endif %}

                        {% if user.is_staff == 0 %}
                        {% if user.is_profesional == 0 %}
                <li><a href="{% url 'base:capacitacion-client' %}">
                        <i class="uil uil-podium"></i>
                        <span class="link-name">Capacitaciones</span>
                    </a></li>
                <li><a href="{% url 'base:visita-client' %}">
                        <i class="uil uil-car-sideview"></i>
                        <span class="link-name">Visitas</span>
                    </a></li>
                <li><a href="{% url 'base:asesoria-client' %}">
                        <i class="uil uil-thumbs-up"></i>
                        <span class="link-name">Asesorias</span>
                    </a></li>
                <li><a href='{% url "base:create-accident" %}'>
                        <i class="uil uil-band-aid"></i>
                        <span class="link-name">Accidentes</span>
                    </a></li>
                <li><a href='{% url "base:contract" %}'>
                        <i class="uil uil-file-contract-dollar"></i>
                        <span class="link-name">Mis Contratos</span>
                    </a></li>
                <li><a href='{% url "base:pagos" %}'>
                        <i class="uil uil-invoice"></i>
                        <span class="link-name">Pagos</span>
                    </a></li>
                <li><a href='{% url "base:reportes" %}'>
                        <i class="uil uil-document-layout-left"></i>
                        <span class="link-name">Informes</span>
                    </a></li>
                {% endif %}
                {% endif %}
            </ul>
            <ul class="logout-mode">
                <li class="mode">
                    <a href="#">
                    </a>

                    <div class="mode-toggle">

                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <section class="dashboard">
        <div class="top">
            <i class="uil uil-draggabledots sidebar-toggle"></i>

            <div class="select-menu">
                <div class="select-btn">
                    {% if user.is_authenticated %}
                    <span class="sBtn-text">Cuenta: {{ user.username }}</span>
                    {% endif %}
                    <i class="uil uil-angle-down"></i>
                </div>

                <ul class="options">
                    <li class="option"><a href="{% url 'base:user-profile' user.username %}">
                            <i class="uil uil-user"></i>
                            <span class="option-text">Perfil</span>
                        </a></li>
                    <li class="option"><a href="{% url 'logout' %}">
                            <i class="uil uil-signout"></i>
                            <span class="option-text">Cerrar sesión</span>
                        </a></li>
                </ul>
            </div>
        </div>
        <div class="dash-content">
            {% block contenido %}

            {% endblock %}
        </div>

    </section>

    <footer>
        <p>&#169 Copyright - ControlRisk 2022</p>
    </footer>

    <script src='{% static "js/main.js" %}'></script>

    {% block javascript %}
    {% endblock %}
</body>

</html>

templates/create_accident.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Registro Contrato - ControlRisk</title>
{% endblock %}

{% block contenido %}
<div class="title">
    <i class="uil uil-band-aid"></i>
    <span class="text">Ingreso de accidente</span>
</div>

<div class="container">
    <form action="#" method="POST" id="form">
        {% csrf_token %}
        <div class="form first">
            <div class="details personal">
                <div class="fields acci">
                    <div class="input-field" id="input-field">
                        <label>Fecha del accidente</label>
                        {{ accidentForm.fecha }}
                        <p class="alert-input" id="alert-input">
                            <i class="uil uil-exclamation-circle"></i> 
                            La fecha no puede ser superior a la actual 
                        </p>
                    </div>
                    <div class="input-field">
                        <label>Descripción del accidente</label>
                        {{ accidentForm.descripcion }}
                    </div>
                    <div class="input-field">
                        <label>Medidas tomadas en el accidente</label>
                        {{ accidentForm.medidas }}
                    </div>
                </div>
            </div>

            <div class="details ID">
                <button class="nextBtn" id="btn">
                    <span class="btnText">Guardar</span>
                    <i class="uil uil-navigator"></i>
                </button>
            </div> 
        </div>
    </form>

    {% if messages %}
    {% for m in messages %}
    <script>
        Swal.fire({
            'tittle': 'Exito',
            'text': '{{ m }}',
            'confirmButtonColor': '#ff131d',
            'confirmButtonText': 'Aceptar',
        })
    </script>
    {% endfor %}
    {% endif %}
</div>
{% block javascript %}
<script src='{% static "js/validate.js" %}'></script>
{% endblock %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Inicio - ControlRisk</title>
{% endblock %}

{% block contenido %}

{% if user.is_authenticated %}

<div class="home-title">
    <img src='{% static "images/ControlRisk_Logo.png" %}' alt="">
    <h2>Intranet Control Risk</h2>
    {% if user.is_staff == 0 %}
    {% if user.is_profesional == 1 %}

    <p>Panel: Profesional</p>

    {% endif %}
    {% endif %}

    {% if user.is_staff == 1 %}
    {% if user.is_profesional == 0 %}

    <p>Panel: Administrador</p>

    {% endif %}
    {% endif %}

    {% if user.is_staff == 0 %}
    {% if user.is_profesional == 0 %}

    <p>Panel: Cliente</p>

    {% endif %}
    {% endif %}
</div>
{% endif %}

{% endblock %}

templates/items.html
<div class="item-container">
    <form action="#" method="POST" id="item-form">
        {% csrf_token %}
        <div class="item-add d-flex flex-wrap align-items-center">
            <div class="fields">
                <div class="input-field" id="input-field-tel">
                    <label>Nombre Item Checklist</label>
                    {{ itemForm.nombre }}
                    <p class="alert-input w-100" id="alert-input" style="position: fixed; top: 235px;">
                        <i class="uil uil-exclamation-circle"></i>
                        Ingrese un Item valido
                    </p>
                </div>
            </div>
            <input type="text" name="id" id="id" value="{{ id }}" style="display: none">
            <button class="nextBtn" type="submit" id="btn" name="btnitem">
                <span class="btnText">AGREGAR ITEM </span>
                <i class="uil uil-plus-circle"></i>
            </button>
            
        </div>
    </form>    
</div>

<script>
    const form = document.getElementById("item-form");
    const input = document.querySelectorAll("#item-form input");
    const expresiones = {
        nombre: /^[a-zA-Z ]{2,50}$/
    }

    const validarFormulario = (e) => {
        switch (e.target.name) {
            case 'nombre':
                if (expresiones.nombre.test(e.target.value)) {
                    document
                        .querySelector("#input-field-tel .alert-input")
                        .classList.remove("alert-input-active");

                    const btn = document.getElementById("btn");
                    btn.disabled = false;
                } else {
                    document
                        .querySelector("#input-field-tel .alert-input")
                        .classList.add("alert-input-active");

                    const btn = document.getElementById("btn");
                    btn.disabled = true;
                }

                inputsClient.forEach((input) => {
                    input.addEventListener("keyup", validarFormulario);
                    input.addEventListener("blur", validarFormulario);
                });
                break;
        }
    }

    input.forEach((input) => {
        input.addEventListener("keyup", validarFormulario);
        input.addEventListener("blur", validarFormulario);
    });
</script>

templates/listar_contratos.html
{% extends 'base.html' %}
{% load static %}

{% block name %}
<title>Clientes - ControlRisk</title>
{% endblock %}

{% block contenido %}
<div class="title">
    <i class="uil uil-file-contract-dollar"></i>
    <span class="text">Contratos registrados</span>
</div>

<div class="button-c">
    <a class="btn" href="{% url 'base:create-contract' %}">Agregar contrato</a>
</div>
<div class=" w">
    <div class="search-box">
        <input type="text" placeholder="Busca aquí...">
    </div>  
</div>

<div class="dash-content">
    <table>
        <thead>
            <tr>
                <th style="text-transform: uppercase">Nro. Contrato</th>
                <th style="text-transform: uppercase">Cliente</th>
                <th style="text-transform: uppercase">Razón Social</th>
                <th style="text-transform: uppercase">Rut Empleado</th>
                <th style="text-transform: uppercase">Nombre Empelado</th>
                <th style="text-transform: uppercase">Fecha Creación</th>
                <th style="text-transform: uppercase">Estado</th>
                <th style="text-transform: uppercase">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for item in entity %}
            <tr>
                <td>{{ item.0 }}</td>
                <td>{{ item.1 }}</td>
                <td>{{ item.17 }}</td>
                <td>{{ item.2 }}</td>
                <td>{{ item.16 }}</td>
                <td>{{ item.8 }}</td>
                {% if item.18 == 1 %}
                <td>
                    <div class="status">
                        <p>ACTIVO</p>
                    </div>
                </td>
                {% else %}
                <td>
                    <div class="status-no">
                        <p>NO ACTIVO</p>
                    </div>
                </td>
                {% endif %}
                <td class="action-container">
                    <div class="action">
                        <a href="{% url 'base:contract-detail' item.0 %}"><i class="uil uil-arrow-up-right"></i></a>
                    </div>
                    <div class="action">
                        <a href=""><i class="uil uil-trash-alt"></i></a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div>
        {% include 'paginator.html' %}
    </div>
</div>
{% endblock %}

templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="container-paginator">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable"><i class="uil uil-angle-left"></i></a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable"><i class="uil uil-angle-right-b"></i></a>
            </li>
        {% endif %}
    </ul>
</div>
<!-- <div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable"><i class="uil uil-angle-left"></i></a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable"><i class="uil uil-angle-right-b"></i></a></span>
    {% endif %}
    <br>
    <br>
</div> -->
{% endif %}

templates/pdf.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style>
    .img-invoice {
        width: 80px;
        text-align: center;
        margin: 0 auto;
    }

    .head {
        text-align: center;
        text-transform: uppercase;
    }

    #invoice thead tr th {
        width: 100%;
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .text-center {
        text-align: center;
    }

    .td-table {
        padding: 8px;
        margin-bottom: 20px;
    }
    .container p,
    b,
    th {
        font-size: 13px;
    }

    td {
        font-size: 12px;
    }

    .aviso {
        margin-top: 10px;
        text-align: center;
        margin-bottom: 20px;
    }

    div > h1 {
        text-align: center;
        margin: 30px;
    }

    img {
        width: 150px;
    }

    .info {
        font-size: 13px !important;
    }

    .firmas {
        width: 100px;
        margin-top: 50px;
        display: flex;
        flex-direction: row;
        justify-content: center;
    }

    .firmass {
        width: 100px;
        margin-top: 50px;
        position: absolute;
    }

    .container-firmas {
        margin: 0 auto !important;
        text-align: center;
        margin-top: 100px !important;
    }
    

</style>

<body>
    <img src="../static/images/ControlRisk_Logo.png" class="img-invoice">
    <p class="head">
        {{ comp.name|upper }}<br>
        {{ comp.rut}}<br>
        {{ comp.direccion|upper }}
    </p>
    <div style="margin: 50px;">
        <h1>****CONTRATO DE SERVICIOS - CONTROLRISK****</h1>
    </div>
    <div class="container">
        <p>
            <b>NRO CONTRATO:</b> {{ contrato.0 }}<br><br>
        </p>
        <table id="invoice">
            <b>RUT EMPRESA CLIENTE :</b><span class="info">  {{ contrato.1 }}</span><br><br>
            <b>RAZÓN SOCIAL EMPRESA CLIENTE :</b> <span class="info">  {{ contrato.11 }}</span><br><br>
            <b>REPRESENTANTE LEGAL EMPRESA CLIENTE :</b> <span class="info">  {{ contrato.13 }}</span><br><br>
            <b>RUBRO EMPRESA CLIENTE :</b> <span class="info">  {{ contrato.15 }}</span><br><br>
            <b>DIRECCIÓN EMPRESA CLIENTE :</b> <span class="info">  {{ contrato.12 }}</span><br><br>
            <b>TELÉFONO EMPRESA CLIENTE :</b> <span class="info">  {{ contrato.14 }}</span><br><br><br>
            <b>RUT EMPLEADO ENCARGADO : <span class="info">  {{ contrato.2 }}</span></b> <br><br>
            <b>NOMBRE EMPELADO ENCARGADO : <span class="info">  {{ contrato.16 }}</span></b> <br><br><br>
            <thead>
                <tr>
                    <th style="width: 33%;">VALOR MENSUAL CONTRATO</th>
                    <th style="width: 34%;">NRO DE CUOTAS</th>
                    <th style="width: 33%;">VALOR TOTAL CONTRATO</th>
                </tr>
            </thead>
            <tbody>
                <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %} class="table" style="width: 100%">
                    <td class="td-table">{{ contrato.17 }}</td>
                    <td class="td-table">{{ contrato.7 }} CUOTAS</td>
                    <td class="td-table">{{ contrato.5 }}</td>
                </tr>
            </tbody>
        </table><br><br><br>
        <div>
            <b>CANTIDAD DE ASESORIAS MENSUALES INCLUIDAS EN EL CONTRATO:</b><span class="info">  {{ contrato.3 }} ASESORIAS</span><br><br>
            <b>CANTIDAD DE CAPACITACIONES MENSUALES INCLUIDAS EN EL CONTRATO :</b> <span class="info">  {{ contrato.4 }} CAPACITACIONES</span><br><br>
            <b>CANTIDAD DE VISITAS A TERRENO MENSUALES INCLUIDAS EN EL CONTRATO :</b> <span class="info">  2 VISITAS</span><br><br>
        </div>
        <div class="aviso">
            <span style="margin-top: 5px">**TODA ACTIVDAD (ASESORIAS, CAPACITACIONES O VISITAS) QUE HAYA SUPERADO EL LIMITE MENSUAL ASIGNADO EN EL CONTRATO SERÁ CARGADO EN SU BOLETA MENSUAL COMO COBROS EXTRAS**</span>
        </div>
        <div>
            <b>CONTRATO VALIDO DESDE :</b><span class="info">  {{ contrato.8 }}</span><br><br>
            <b>CONTRATO VALIDO HASTA :</b> <span class="info">  {{ contrato.10 }}</span><br><br>
            <b>FECHA PAGO DE PRIMERA CUOTA :</b> <span class="info">  {{ contrato.9 }}</span><br><br>
        </div>
    </div><br><br><br><br><br><br><br><br><br><br><br><br>
    <div>
        {% if contrato.18 == '0' %}
            <b>ESTADO DEL CONTRATO : <span class="info"> FINALIZADO</span></b><br><br>
        {% else %}
            <b>ESTADO DEL CONTRATO : <span class="info"> CONTRATO VIGENTE</span></b><br><br>
        {% endif %}
    </div>
    <div>
        {% if contrato.6 == '1' %}
            <b>ESTADO DE PAGO DEL CONTRATO : <span class="info"> CONTRATO PAGADO</span></b><br><br>
        {% else %}
            <b>ESTADO DE PAGO DEL CONTRATO : <span class="info"> PAGANDO</span></b><br><br>
        {% endif %}
    </div>
    <div class="container-firmas" style="margin-top: 100px">     
        <div class="firmas">
            <div class="firma-container">
                <img src="../static/images/firma2.png" alt="">
                <div>
                    <p >FIRMA VICEPRESIDENTE JUNIOR</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container-firmas" style="margin-top: 100px">     
        <div class="firmas">
            <div class="firma-container">
                <img src="../static/images/firma2.png" alt="">
                <div>
                    <p >FIRMA VICEPRESIDENTE JUNIOR</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container-firmas" style="margin-top: 100px">     
        <div class="firmas">
            <div class="firma-container">
                <img src="../static/images/firma2.png" alt="">
                <div>
                    <p >FIRMA VICEPRESIDENTE JUNIOR</p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>